version: '3.8'

services:
  flask-app:
    build: 
      context: app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my-network

  stats-script:
    build: 
      context: script
      dockerfile: Dockerfile
    networks:
      - my-network
networks:
  my-network:
