apiVersion: apps/v1
kind: Deployment
metadata:
  name: script-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: script
  template:
    metadata:
      labels:
        app: script
    spec:
      containers:
      - name: script
        image: viktor891/script:latest
